version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    binary: "opentofu-provider-multipass_v{{ .Version }}"

archives:
  - format: zip
    name_template: "opentofu-provider-multipass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "opentofu-provider-multipass_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## What's Changed
    
    See the [CHANGELOG](https://github.com/sh05/terraform-provider-multipass/blob/main/CHANGELOG.md) for more details.
  footer: |
    ## Docker Images
    
    - `docker pull ghcr.io/sh05/terraform-provider-multipass:{{ .Tag }}`

changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"